### ISSUE TITLE
Feature Request: Numerical Syntax  

### ISSUE THREAD

**Issue by JoshC1994** [davidusb-geek/emhass#104]
**Describe the bug**
The Syntax of numbers shown in the "Last Run Optimisation Results Table" sometimes displaying as scientific numbers.
![image](https://github.com/davidusb-geek/emhass/assets/85683627/fa689976-6448-41e9-a1df-57c600f4ef76)

**Why**
The fact may be simply due to the input data EMHASS is being fed and the maths being calculated so that the resulting number is too great for the plotly table to display.

**Fix**
Would it cause too many issues with resolution if EMHASS only considered data and calculated the resultant to say 2 decimal points. I would think that any more resolution is only adding complexity and would require unnecessary compute resources.
Maybe the decimal count could be set via config?       

I might be missing something but in most use cases I think that 2 decimal places would be enough resolution.

**Comment by purcell-lab** [comment]
Thanks @JoshC1994 , I have been having this issue as well.

@davidusb-geek while you are fixing the rounding could I suggest some additional improvements:

Could I suggest that all the power values be rounded to 0 decimal places.

P_PV and P_Load are already displayed as int, but the other P_ variables are displayed with a lot of unnecessary precision and it would be good if they could also be displayed as int, cost_profit & cost_fun could also potentially be rounded to 2 decimal places:

![Screenshot 2023-08-17 07 00 45](https://github.com/davidusb-geek/emhass/assets/79175134/703fe3f3-77dd-4572-b8de-f0f2d19d97a3)

**Comment by davidusb-geek** [comment]
Solved here: #105
Will be available in the next release.

**Comment by kcoffau** [comment]
+1 thank you! @davidusb-geek 

Appreciate everything you do for this project!

**Comment by purcell-lab** [comment]
Nice work, much more readable:

![image](https://github.com/davidusb-geek/emhass/assets/79175134/0a153976-dfbe-40c6-bc0b-abf2d4cacbfe)

**Comment by davidusb-geek** [comment]
Great! Closing this as completed.

**Comment by purcell-lab** [comment]
I know this issue is closed, but the Power values seem to have snuck back in with unnecessary decimal (.0) again.
![image](https://github.com/davidusb-geek/emhass/assets/79175134/3e96ee90-1cab-4bea-ade1-f0c04f9ceff3)

**Comment by davidusb-geek** [comment]
This is solved in the (just-to-be-released) new release.
