### ISSUE TITLE
Initial and target SOC

### ISSUE THREAD

**Issue by nateguchi** [davidusb-geek/emhass#113]
Hi,

I run the optimisation every day at midnight and I'd like it to take into account the current state of the battery as a starting point but don't care too much about where the battery level ends. At the moment if I pass `SOCtarget` to the dayahead-optim call, it doesn't appear to be fully honoured as a starting value.

**Comment by g1za** [comment]
In the dayahead optim this is not possible. The idea behind that is that given you are at a desired state in 24h you will be at the same, so SOC_init=SOC_final=SOC_target. You can pass a desired soc_final parameter via curl but it will be ignored and the one from config.yaml is used. If you want to define the start and end SOC, at the moment, you have to switch to MCP optim.
