### ISSUE TITLE
Question - how to install latest version into Home Assistant?

### ISSUE THREAD

**Issue by radoslavius** [davidusb-geek/emhass#121]
Hi
today Home Assistant installed version 0.4.2. How can I install a newer version as an addon?
Thanks

**Comment by davidusb-geek** [comment]
I don't quite understand your question but v0.4.2 is the latest version

**Comment by radoslavius** [comment]
I apologize for the misunderstanding. I was confused by the latest version of EMHASS 0.5.1 and I didn't realize that the addon is versioned differently.
