### ISSUE TITLE
Dynamic current control loop for inverter heat pump

### ISSUE THREAD

**Issue by giuseppe072000** [davidusb-geek/emhass#127]
For  Dynamic current control what settings I need to make to user 95% from PV production with a inverter heat pump?

For heat pump is possible to :
-switch on /off ,
-to reduce with 50% power of the device /Eco mode ,

to change flow temperature 25-60C
 
to chose another temperature curve
-to change from heating to hot water
to read temperature from boiler
to change hot water temperature 25-60C from boiler
-to read flow and return temperature

**Comment by davidusb-geek** [comment]
> For Dynamic current control what settings I need to make to user 95% from PV production with a inverter heat pump?

I don't quite understand this question.

With EMHASS you will have a continuous power consumption for a heat pump. Now you need to translate yourself that power consumption into a temperature setting.
