### ISSUE TITLE
shell command in configuration.yaml

### ISSUE THREAD

**Issue by tomekl1978** [davidusb-geek/emhass#14]
incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line

**Comment by davidusb-geek** [comment]
Hi, you should be more specific here. What is the shell command that you are trying to use? What are you trying to achieve, what kind of optimization?

**Comment by tomekl1978** [comment]
Shell command from instructions in Home Assisstant. 

```
shell_command:
  dayahead_optim: curl -i -H "Content-Type: application/json" -X POST -d '{}' http://localhost:5000/action/dayahead-optim
  publish_data: curl -i -H "Content-Type: application/json" -X POST -d '{}' http://localhost:5000/action/publish-data 
```

**Comment by davidusb-geek** [comment]
Ok, you'll need to provide more information, otherwise it'll be very hard to help you solve this. Please post the complete logs from the "Log" pane in the add-on. 

This fails when running the "dayahead-optim" or the "publish_data"?

May be share you yaml add-on configuration...

**Comment by davidusb-geek** [comment]
Hi, just closing this as no more information was provided and impossible to solve (if it is a real issue) as it is.

**Comment by henne49** [comment]
when entering the shell_command statement into Visual studio, you get the following error message displayed: incomplete explicit mapping pair; a key node is missed.

Also the check config yaml element shows: Error loading /config/configuration.yaml: mapping values are not allowed here

the provide shell code command does not work in latest home assistant 2022.8.2

**Comment by davidusb-geek** [comment]
Hi

**Comment by henne49** [comment]
Got it fixed, you have to remove the space after the Content-Type: application does not work, the below commands work, please just adjust the documentation.

thx

shell_command:
  dayahead_optim: curl -i -H 'Content-Type:application/json' -X POST -d '{}' http://localhost:5000/action/dayahead-optim
  publish_data: curl -i -H "Content-Type:application/json" -X POST -d '{}' http://localhost:5000/action/publish-data

**Comment by davidusb-geek** [comment]
Ok perfect. Thank you.

I actually realized that the documentation was outdated, I actually implemented those `shell_command` using this syntax:
```
shell_command:
  dayahead_optim: "curl -i -H 'Content-Type: application/json' -X POST -d '{}' http://localhost:5000/action/dayahead-optim"
```
So I wasn't having any problem with that.
And your solution is also valid I guess.
I just updated the documentation

**Comment by henne49** [comment]
I tried that as well, but it did not work for me. Thank you for your great tool! I was trying to find exactly what you are doing, as this is last bit to fully automate and save energy.
