### ISSUE TITLE
Feature Request: Reason for infeasible optimization result

### ISSUE THREAD

**Issue by sti0** [davidusb-geek/emhass#180]
Today when a optimization result is infeasible we may get a warning in the container / addon log.

![image](https://github.com/davidusb-geek/emhass/assets/18382402/d7bf12ba-e4c2-4296-804c-91969941b93c)

This warning is not accessable by web ui or the `sensor.optim_status` sensor entity.

Therefore I would suggest to add the reason of a infeasible optimization result as an additional attribute to `sensor.optim_status`. This then could be used in automations, alerts and notifications. Furthermore it should be displayed in the Web UI as well.

**Comment by davidusb-geek** [comment]
I don't know about this one. Infeasible status are difficult to catch because there could a huge amount of reasons for a failing optimization.
You happend to stump on the only case that is actually catched and where a warning message is issued.
