### ISSUE TITLE
Docker standalone image build fail

### ISSUE THREAD

**Issue by davidusb-geek** [davidusb-geek/emhass#205]
Hi @GeoDerp.
The workflow for building the docker standalone image is failing.
I don't totally understand why.
We were previously building usin this image:
```
FROM python:3.11-slim-buster
```
That worked fine. 
Any ideas to solve this if possible?

**Comment by davidusb-geek** [comment]
Tested everything and released new versions, everything works great! 
But this workflow is failing.

**Comment by GeoDerp** [comment]
No worries I'll have a look at this today 👍
