### ISSUE TITLE
Huge icons on webui

### ISSUE THREAD

**Issue by davidusb-geek** [davidusb-geek/emhass#230]
Hi @GeoDerp 
I don't know if you can see this same issue but in my webui there are now huge icons:

![image](https://github.com/davidusb-geek/emhass/assets/32926550/8ca11437-3a7c-4015-ba37-c95d95221029)

These icons where normal size on upper right corner on v0.8.1

**Comment by GeoDerp** [comment]
Interesting, definitely nothing changed from 0.8.1.
By webui, it's like a PWA? 
I'll have a look to see if there is any max sizing on  the buttons. If not I'll set some. 
It may be a good idea to have a PR that just focuses on improved PWA support.

**Comment by purcell-lab** [comment]
I get large icons on mobile but not my laptop.

![Screenshot_20240312-122546](https://github.com/davidusb-geek/emhass/assets/79175134/48c9f15a-3cb5-44d6-a8a1-73c9709a35e9)

**Comment by GeoDerp** [comment]
Thanks @michaelpiron,  It looks like the same issue with some sort of styling not being propperly enabled. Im having a look at this now.

**Comment by GeoDerp** [comment]
Is it possible that one of your can test this out: https://github.com/GeoDerp/emhass/tree/index-icon-fix

**Comment by GeoDerp** [comment]
Just added an JS function that checks if stylsheet exists, if not adds it. *(redundancy)*

**Comment by GeoDerp** [comment]
Dad had the idea it could be a DNS issue. He might not be wrong. Ie. If you're using DNS it may not be getting called probably inside the webui. The JS function may help with this I'm not sure.

**Comment by GeoDerp** [comment]
Let me know if this has been fixed for you guys.  👍

**Comment by michaelpiron** [comment]
> Thanks @michaelpiron, It looks like the same issue with some sort of styling not being propperly enabled. Im having a look at this now.
> 
> Its kinda annoying that this doesn't seem to be an issue on my end. Does the other elements styling look correct? _(buttons have shadows, etc)_. If you run http://yourhaip:5000, does it still look that same.
> 
> Also @michaelpiron , is your mobile an IPhone? Mine is a Android.

Hi @GeoDerp , could it be that you addressed the wrong person? I don’t recall this issue.

**Comment by purcell-lab** [comment]
Yes I do get styling from the webUI interface.

![Screenshot_20240314-070110](https://github.com/davidusb-geek/emhass/assets/79175134/018c98b5-1a97-4543-989c-08be06cad4a2)

**Comment by GeoDerp** [comment]
> Yes I do get styling from the webUI interface.
> 
> ![Screenshot_20240314-070110](https://github.com/davidusb-geek/emhass/assets/79175134/018c98b5-1a97-4543-989c-08be06cad4a2)
> 

Yeah interesting. You do, but even things like the basic info box doesn't show up.

**Comment by GeoDerp** [comment]
Sorry @michaelpiron , that was my bad.meant that to be @purcell-lab. 

@purcell-lab , could you clear the app cache in the android settings then force killing the app and rerunning? 

![Screenshot_20240314-082926.png](https://github.com/davidusb-geek/emhass/assets/18461782/2f952cf0-9c1f-41bb-8956-3fa2549c7d39)

![Screenshot_20240314-082813.png](https://github.com/davidusb-geek/emhass/assets/18461782/354939dc-81ef-4f1f-9f93-aed99c38dc7d)

**Comment by purcell-lab** [comment]
Cache cleared, no change unfortunately.

**Comment by GeoDerp** [comment]
> Cache cleared, no change unfortunately.

@purcell-lab does the buttons (svg and actions) work? 
If so I may just embed the CSS file.

**Comment by purcell-lab** [comment]
Buttons are functional with large icons.

Not sure how to test svg?

**Comment by GeoDerp** [comment]
@purcell-lab could you test this for me. Made a EMHASS fork, Bellow are the steps to build emhass-add-on using EMHASS from my repo and branch. *(feel free to keep your original EMHASS, just running this version on a separate port)*


```bash
cd ~/addons/
git clone https://github.com/davidusb-geek/emhass-add-on
sed -i.bak '/image:/ s/./#&/' ~/addons/emhass-add-on/emhass/config.yml
sed -i.bak "s/build_version:.*/build_version: addon-git/g"  ~/addons/emhass-add-on/emhass/build.yaml
repo=https://github.com/GeoDerp/emhass.git
branch=index-icon-fix
sed -i.bak "s%build_repo:\s.*%build_repo: $repo%g"  ~/addons/emhass-add-on/emhass/build.yaml
sed -i.bak "s/build_branch:\s.*/build_branch: $branch/g"  ~/addons/emhass-add-on/emhass/build.yaml
```

**Comment by GeoDerp** [comment]
Update, tested with Nabu Casa . No problems with current version or fork. @davidusb-geek or @michaelpiron . If your still having issues if you could test the fork above and see if that fixes your current solution that would be great.

**Comment by purcell-lab** [comment]
I haven't updated since 0.8.4.

Icons are now a good size on laptop and mobile:

![Screenshot_20240318-201708 (2)](https://github.com/davidusb-geek/emhass/assets/79175134/dd84e7cb-22da-4b76-bf60-fdd1b6927970)

Graphs are also a lot more usable on mobile as well, I even get yellow for PV ;-)

![Screenshot_20240318-201720](https://github.com/davidusb-geek/emhass/assets/79175134/531651a4-a140-4199-8e7b-ebac1ebf54b6)

Great work..

**Comment by GeoDerp** [comment]
> I haven't updated since 0.8.4.
> 
> Icons are now a good size on laptop and mobile:
> 
> ![Screenshot_20240318-201708 (2)](https://github.com/davidusb-geek/emhass/assets/79175134/dd84e7cb-22da-4b76-bf60-fdd1b6927970)
> 
> Graphs are also a lot more usable on mobile as well, I even get yellow for PV ;-)
> 
> ![Screenshot_20240318-201720](https://github.com/davidusb-geek/emhass/assets/79175134/531651a4-a140-4199-8e7b-ebac1ebf54b6)
> 
> Great work..

I guess it was a cache problem after all. 
@davidusb-geek, if you think the PR is still good (replacing urls with relatives). free to merge it.

Otherwise I'll close it, and I may make another PR with just the CSS JS function removed. As, I believe it slows down the page loading time.

**Comment by GeoDerp** [comment]
@purcell-lab, the diagram is just an inverted colour of the light mode. PV being yellow is an accidental benefit. 😂

**Comment by GeoDerp** [comment]
@davidusb-geek, feel free to close this issue after reading this. 👍🏼

**Comment by davidusb-geek** [comment]
> @davidusb-geek, feel free to close this issue after reading this. 👍🏼

Ok but what do you recommend regarding PR #239?
If load times are affected then it should be better to do this?:
> Otherwise I'll close it, and I may make another PR with just the CSS JS function removed. As I believe it slows down the page loading time.

**Comment by GeoDerp** [comment]
@davidusb-geek , If you have any issues @ me and ill help revert.

**Comment by davidusb-geek** [comment]
Ok, I merged. Then will test it and see how it goes.

**Comment by davidusb-geek** [comment]
Seems solved to me.
Closing
