### ISSUE TITLE
Feature Request: Support for limiting amount that can be exported to the grid

### ISSUE THREAD

**Issue by philjohn** [davidusb-geek/emhass#235]
**Describe the bug**

At present there is a setting for the amount you can pull in from the grid, however, as Distributed Solar PV continues to grow, many network operators are placing limits on how much power can be sent back to the grid - e.g. g100 export limitation in the UK.

**Expected behavior**

A new configuration setting that allows the maximum export to be defined

**Comment by davidusb-geek** [comment]
Hi yes for now this a limitation. The maximum power from and to the grid is the same.
We will split that into separate configurable parameters

**Comment by kcoffau** [comment]
+1 on this.

**Comment by davidusb-geek** [comment]
Implemented in the fresh release. A new configuration parameter `P_to_grid_max` was added. 
Closing as completed
