### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by WimGo** [davidusb-geek/emhass#270]
The documentation, at https://emhass.readthedocs.io/en/latest/intro.html#the-publish-data-specificities mentions these variables:
`sensor_power_load_no_var_loads, sensor_power_load, sensor_power_washing_machine, sensor_power_load`.
According to my understanding, in all these cases, the first underscore should be a dot, as in:
`sensor.power_load_no_var_loads, sensor.power_load, sensor.power_washing_machine, sensor.power_load`

**Comment by WimGo** [comment]
I pull this issue. Probably I need to read more.

**Comment by davidusb-geek** [comment]
Hi yes those are errors, there should be a dot instead of underscores after sensor.
