### ISSUE TITLE
Missing EMHASS_button.svg

### ISSUE THREAD

**Issue by davidusb-geek** [davidusb-geek/emhass#281]
Hi @GeoDerp ,
This file is missing and needed from the EMHASS ad-on README.
Could you please add it to docs/images?

**Comment by GeoDerp** [comment]
> Hi @GeoDerp ,
> This file is missing and needed from the EMHASS ad-on README.
> Could you please add it to docs/images?

Greetings @davidusb-geek ,
The svg file is stored on: https://github.com/davidusb-geek/emhass/pull/276
Merging that on the EMHASS repo will fix the missing svg here. 
I'm storing all the svg files on the single repo so modifying one file will affect both repos. (The aim is easier maintenance)
Happy to change this if required. 👍

**Comment by davidusb-geek** [comment]
Ok thanks!
Missed that...
