### ISSUE TITLE
Solcast shows values at night

### ISSUE THREAD

**Issue by a8291** [davidusb-geek/emhass#323]
Hey,
When doing a dayahead optimization at noon with configured Solcast EMHASS is showing me PV production for the coming night. Doesn't emhass take into account what time it is or am I doing sth wrong?

The one on the screenshot was triggered just now at 11am.
![Screenshot_20240707_104957_Home Assistant](https://github.com/davidusb-geek/emhass/assets/23558222/e81fa2a8-0647-4188-b70c-8e16635a7d78)

**Comment by GeoDerp** [comment]
> Hey,
> When doing a dayahead optimization at noon with configured Solcast EMHASS is showing me PV production for the coming night. Doesn't emhass take into account what time it is or am I doing sth wrong?
> 
> The one on the screenshot was triggered just now at 11am.
> ![Screenshot_20240707_104957_Home Assistant](https://github.com/davidusb-geek/emhass/assets/23558222/e81fa2a8-0647-4188-b70c-8e16635a7d78)
> 

Greetings @a8291 ,
I'm not quite sure 100%. 
Maybe check your timezones on HA and/or the configuration.
If your running EMHASS not in HA (in standalone) you may need to pass in the `-e TZ=Country/State` in the docker run.
Other then that maybe the Solcast rooftop is set up wrong? 
Let me know once you check these thing if they are still wrong and I will have a look at the code.

**Comment by a8291** [comment]
I am running as an addon of HA. My time zone settings are correct in HA. The rooftop location of Solcast is correctly setup.

**Comment by GeoDerp** [comment]
Sorry forgive me, I have just re-read your message. Looking at the screenshot seems fine by me.
Is it okay if you can elaborate on what "for the coming night" means?
The first element looks like 11:00am to me +2:00 indicating `UTC+2:00`

**Comment by a8291** [comment]
After setting the freq to 30 minutes it makes more sense. Now I don't get any PV production when it's dark. That was what I meant with night. Sorry the confusion. So it seems to be related to the frequency. 
![Screenshot_20240707_193926_Home Assistant](https://github.com/davidusb-geek/emhass/assets/23558222/5a7feb5e-795e-4c37-bb63-49689b12e850)
