### ISSUE TITLE
Feature Request: Cost/profit comparison

### ISSUE THREAD

**Issue by smefa** [davidusb-geek/emhass#339]
Would it be possible to add a cost value that is calculateed without any battery usage as a comparison?
You could use this to see how much you potentially save using battery storage.

**Comment by davidusb-geek** [comment]
Yes it can be done and could be interesting. It will need some code tweaking to get it done. I will look into it when I have the time

**Comment by purcell-lab** [comment]
I have been doing some work using Riemann sum and utility meters to calculate the savings and cost benefits of both solar and battery.

https://community.home-assistant.io/t/add-solar-cost-saving-option-to-native-energy-dashboard/376143/4?u=markpurcell

**Comment by davidusb-geek** [comment]
Yes probably something to do better directly in HA.
Closing

**Comment by smefa** [comment]
I don't see how you could calculate the projected missed savings, only the outcome. Am I wrong?
But anyhow, it's ok to close it since it is a niche request.
![image](https://github.com/user-attachments/assets/cb38e63f-386e-4b84-9039-7e34956b29d6)

**Comment by davidusb-geek** [comment]
I just went to the link provided my Mark and saw that he is able to separetly compute PV saving, Battery saving and PV+battery savings. So the missed savings of adding the battery are just the opposite of the battery savings, right?

**Comment by smefa** [comment]
Yes, I guess it would work if you use the battery and show historic values. 
I don't see how it would work for the prediction. But anyhow, we can drop this since it is not that important.

**Comment by davidusb-geek** [comment]
Ok.
If you are interested a manual script could also achieve the kind of comparison that you are looking for.
For example this script here does just that, compare different use cases (with and without PV and batteries):
https://github.com/davidusb-geek/emhass/blob/master/scripts/use_cases_analysis.py

**Comment by smefa** [comment]
Thanks
