### ISSUE TITLE
Configuration text for logging levels correction

### ISSUE THREAD

**Issue by purcell-lab** [davidusb-geek/emhass#378]
**Describe the bug**
The text help under logging doesn't seem to be correct.

**Screenshots**
![Screenshot_20241119-084724](https://github.com/user-attachments/assets/2af1c80d-ffa6-42df-b12b-b4ea5c3a6553).

**Comment by GeoDerp** [comment]
> **Describe the bug**
> The text help under logging doesn't seem to be correct.
> 
> **Screenshots**
> ![Screenshot_20241119-084724](https://github.com/user-attachments/assets/2af1c80d-ffa6-42df-b12b-b4ea5c3a6553).
> 

🤦, will fix this. Thanks @purcell-lab
