### ISSUE TITLE
Cost function can't be chosen v0.11.2

### ISSUE THREAD

**Issue by RikBast** [davidusb-geek/emhass#393]
**Describe the bug**

Can’t choose ‘profit’ as an option in the config with v0.11.2

**To Reproduce**
Open config and try to change cost function and save

**Expected behavior**
Be able to choose between profit, cost, self-consumption

**Home Assistant installation type**
 - Home Assistant OS
 
**Your hardware**
- OS: MacOs with VM
- Architecture: amd64, armhf, armv7, aarch64

**EMHASS installation type**
 - Add-on

**Additional context**

**Comment by GeoDerp** [comment]
I believe this was fixed in PR: https://github.com/davidusb-geek/emhass/pull/375
This will be rolled out in a new release.
