### ISSUE TITLE
Feature request: Nord Pool integration get data from within HA

### ISSUE THREAD

**Issue by BDVGitHub** [davidusb-geek/emhass#394]
Since there is a [Nord Pool integration](https://www.home-assistant.io/integrations/nordpool/) for Home Assistant is it possible to use this data to load in Emhass?

Instead of doing this:
[Example using the Nordpool integration](https://emhass.readthedocs.io/en/latest/forecasts.html#example-using-the-nordpool-integration)

The Nordpool integration provides spot market electricity prices (consumption and production) for the Nordic, Baltic and part of Western Europe. An integration for Home Assistant can be found here: https://github.com/custom-components/nordpool

After setup the sensors should appear in Home Assistant for raw today and tomorrow values.

The subsequent shell command to concatenate today and tomorrow values can be for example:

shell_command:
  trigger_nordpool_forecast: "curl -i -H \"Content-Type: application/json\" -X POST -d '{\"load_cost_forecast\":{{((state_attr('sensor.nordpool', 'raw_today') | map(attribute='value') | list  + state_attr('sensor.nordpool', 'raw_tomorrow') | map(attribute='value') | list))[now().hour:][:24] }},\"prod_price_forecast\":{{((state_attr('sensor.nordpool', 'raw_today') | map(attribute='value') | list  + state_attr('sensor.nordpool', 'raw_tomorrow') | map(attribute='value') | list))[now().hour:][:24]}}}' http://localhost:5000/action/dayahead-optim"

**Comment by davidusb-geek** [comment]
Hi and sorry but I don't understand your feature request. Isn't that shell command that you are posting good enough? What is the new feature that you are seeking? That is how it works, you pass the data available from the many different providers out there as argument data in a shell command.

**Comment by BDVGitHub** [comment]
What I want to say now that Home Assistant has added Nord Pool as an integration. 
![afbeelding](https://github.com/user-attachments/assets/59e2b026-78aa-4af9-8fc8-c1956357e2da)

Is it possible to automatically retrieve the Nord Pool data contained in Home Assistant? So that you no longer have to use the shell command? But only have to indicate e.g. in the config file that you use Nord Pool data available in Home Assistant?
![afbeelding](https://github.com/user-attachments/assets/73a6b9b0-d94d-421e-a4b6-b7d04930a828)
![afbeelding](https://github.com/user-attachments/assets/e8972e9d-16f5-4a42-8fe7-fa7a98b92b62)
![afbeelding](https://github.com/user-attachments/assets/aa094786-c690-419d-aa4f-15acc48f9a9e)

**Comment by davidusb-geek** [comment]
I understand that it can be even easier to just tell EMHASS to use Nordpool and it connects directly with HA and retrieves the data.
But in reality this is not a smart move because each integration is unique, so if we do this for Nordpool then we need to do it for Amber, etc. The same principle for the many options to provide solar forecasts for example. The approach that we took is that data coming from an external provider should passed to EMHASS at runtime. So possibly we need to focus on how to ease in the setup of shell commands. The blueprints are a good option, provide a blueprint for each external data provider. Open to contributions on this.

**Comment by davidusb-geek** [comment]
Closing as not planned

**Comment by BDVGitHub** [comment]
A think I understand what you mean, the blueprint in HomeAssistant then acts as a software connector to let the HA integration exchange data with Emhass. Is this correct?
