### ISSUE TITLE
Config file uses arrays of single-element dicts: ??

### ISSUE THREAD

**Issue by smurfix** [davidusb-geek/emhass#48]
I wonder what your motivation is to use arrays of single-element dicts virtually everywhere in your configuration file.
IMHO that's unnecessarily complex. Would you accept a patch that drops this?

**Comment by davidusb-geek** [comment]
Yes totally agree with you. This was the first solution I implemented but is awful and over complex as you said.
If you can help with this it would be appreciated. Just be careful to test the web_server.py after the changes because this file is not unit tested.

**Comment by smurfix** [comment]
Working on it. :-)

**Comment by davidusb-geek** [comment]
Hi, did you managed to test your changes? It works as expected?

**Comment by smurfix** [comment]
Not yet, too much other stuff on my plate at the moment. Coming soon.

**Comment by davidusb-geek** [comment]
Sure no problem, just asking because I will be adding a bunch of new stuff soon, so just looking to avoid code conflicts. But if any it should not be so hard to solve with git.

**Comment by davidusb-geek** [comment]
If you know how to unittest the web_server.py that uses Flask, any advice will be greatly appreciated.

**Comment by davidusb-geek** [comment]
Closing as completed #69
