### ISSUE TITLE
Feature Request: Color for PV

### ISSUE THREAD

**Issue by purcell-lab** [davidusb-geek/emhass#70]
Could I request that the P_PV graph be colored yellow.

![Screenshot 2023-04-10 10 18 32](https://user-images.githubusercontent.com/79175134/230803518-00d86e41-96e3-495e-a156-ec859b158848.png)

**Comment by davidusb-geek** [comment]
This will be available in the next release. However, PV power may not be yellow, but all colors are guaranteed to be different.

**Comment by davidusb-geek** [comment]
This is addressed in the latest release
