### ISSUE TITLE
prod/load_cost unit_of_measurement €/kWh & $/kWh 

### ISSUE THREAD

**Issue by purcell-lab** [davidusb-geek/emhass#78]
https://github.com/davidusb-geek/emhass/blob/6b1a1b35423a131a8bb4905d9be8d90a3f7f7030/src/emhass/utils.py#L139

I suspect the unit_of_measurement should be €/kWh, but also the ability to support other currencies like $/kWh.

**Comment by davidusb-geek** [comment]
Yes, you're right. This should be €/kWh. That line in the code are just the default values. But you can pass your custom values at runtime when calling the shell command for publish data. So in your case you can certainly pass $/kWh

**Comment by davidusb-geek** [comment]
I'm updating this right now

**Comment by davidusb-geek** [comment]
Fixed on latest release
