### ISSUE TITLE
Feature Request: unit_prod_price & unit_load_cost forecasts

### ISSUE THREAD

**Issue by purcell-lab** [davidusb-geek/emhass#82]
Thanks for implementing the price and cost sensors.

It would be great if this could be extended (like the other EMHASS published sensors) to include the future forecasts as an atribute.

![Screenshot 2023-05-28 14 31 55](https://github.com/davidusb-geek/emhass/assets/79175134/cfe486d7-005b-4296-9a84-08ad61b74bcd)

![Screenshot 2023-05-28 14 35 11](https://github.com/davidusb-geek/emhass/assets/79175134/c27230ad-d5ce-403b-b204-35de888132a0)

![Screenshot 2023-05-28 14 36 41](https://github.com/davidusb-geek/emhass/assets/79175134/8f3d90eb-768f-4d1e-89e7-a18817397828)

**Comment by davidusb-geek** [comment]
Hi, yes sure. This should be an easy fix. It can be added in the next release.

**Comment by purcell-lab** [comment]
I don't seem to be getting much through these attributes ;-(

They are all coming out as 0.0.

![image](https://github.com/davidusb-geek/emhass/assets/79175134/45aa7d68-86b7-4bd2-b470-25a969ab4e44)
![image](https://github.com/davidusb-geek/emhass/assets/79175134/5d9e8db8-b229-4489-b07d-261384983f91)

**Comment by Octofinger** [comment]
Same issue here. It seems the value is rounded to nearest whole number at some point and then converted to a float again. Here's what it looks like for me (sorry for the large screenshot but I wanted to the the 2.0 values included):
![image](https://github.com/davidusb-geek/emhass/assets/34031086/d6f973ae-dba2-41b2-abea-5d4982c8265b)

**Comment by davidusb-geek** [comment]
This is an easy fix. It is already solved here: #91
It will be available on the next release.

**Comment by davidusb-geek** [comment]
I've just published a new release, it should work as expected.

**Comment by purcell-lab** [comment]
Unfortunately I am still doing the rounded to 0.0 on the forecasts so this issue should be reopened.

![Screenshot_20230701-082255](https://github.com/davidusb-geek/emhass/assets/79175134/a88723f0-4aa0-43e6-89a8-53066f2df986)

**Comment by davidusb-geek** [comment]
Ok, it works as expected on the tests. I'll take a look at this

**Comment by purcell-lab** [comment]
Let me know if you want me to test any code.

**Comment by davidusb-geek** [comment]
Thanks Mark. Just a question this is happening for both unit_prod_price and unit_load_cost?

**Comment by Octofinger** [comment]
I can concur. I have the same issue after updating to 0.4.13. Both `unit_prod_price` and `unit_load_cost` have attributes rounded to nearest integer, even if they are floats.
![image](https://github.com/davidusb-geek/emhass/assets/34031086/22d9d7d2-59e1-4b80-994a-cbc2225ff480)

![image](https://github.com/davidusb-geek/emhass/assets/34031086/dfad3578-df4d-4749-9cee-9541f6e8407e)

**Comment by purcell-lab** [comment]
> Thanks Mark. Just a question this is happening for both unit_prod_price and unit_load_cost?

Yes both are being rounded to 0.0

**Comment by purcell-lab** [comment]
This is amazing:
https://chat.openai.com/share/6a5bd9ed-f67f-4c32-a5d7-96e06de1255d

![image](https://github.com/davidusb-geek/emhass/assets/79175134/50f2b6cd-508f-476c-8508-8c21f5cec00a)

--- retrieve_hass.py
+++ retrieve_hass_modified.py
@@ -231,7 +231,7 @@
             datum[entity_id.split('sensor.')[1]] = vals_list[i]
             forecast_list.append(datum)
         data = {
-            "state": str(state),
+            "state": "{:.2f}".format(state),
             "attributes": {
                 "unit_of_measurement": unit_of_measurement,
                 "friendly_name": friendly_name,
@@ -307,7 +307,7 @@
                                                     friendly_name, "scheduled_forecast", state)
         else:
             data = {
-                "state": str(state),
+                "state": "{:.2f}".format(state),
                 "attributes": {
                     "unit_of_measurement": unit_of_measurement,
                     "friendly_name": friendly_name


--- retrieve_hass_modified.py
+++ retrieve_hass_modified_v2.py
@@ -223,7 +223,7 @@
         list_df = copy.deepcopy(data_df).loc[data_df.index[idx]:].reset_index()
         list_df.columns = ['timestamps', entity_id]
         ts_list = [str(i) for i in list_df['timestamps'].tolist()]
-        vals_list = [str(np.round(i)) for i in list_df[entity_id].tolist()]
+        vals_list = [str(np.round(i, 2)) for i in list_df[entity_id].tolist()]
         forecast_list = []
         for i, ts in enumerate(ts_list):
             datum = {}

**Comment by davidusb-geek** [comment]
Some of the nice usages for chatgpt ;-)
