### ISSUE TITLE
Feature Request: Pass an array of hourly load_peak_hours costs instead of a constant value ( ex. prices from Tibber)

### ISSUE THREAD

**Issue by potsch** [davidusb-geek/emhass#83]
Is it possible to pass an array of hourly load_peak_hours costs instead of a constant value?
My grid cost comes from tibber and I would wish to pass a new value hourly.
Is that possible in the future or can you offer me a workaround?

**Comment by davidusb-geek** [comment]
Hi. No need for a "workaround", this fully supported.
Take a look at the docs, there are example that you can copy to achieve that. You just need to pass the data as list of values inside the shell command

**Comment by davidusb-geek** [comment]
You can directly use the community forum for this type of questions, is a great source of help.
This user has your exact same use case, but he's using the Nordpool prices directly: https://community.home-assistant.io/t/emhass-an-energy-management-for-home-assistant/338126/292?u=davidusb

And the shell command for this type of task from the documentation:
https://emhass.readthedocs.io/en/latest/forecasts.html#example-using-the-nordpool-integration

I'm closing this but feel free to reopen if you need more help.
