### ISSUE TITLE
Feature request: Grid availability

### ISSUE THREAD

**Issue by ga-it** [davidusb-geek/emhass#87]
Hello

Thank you for amazing work.

South Africa currently has significant power constraints. As such, power is rotationally shedded according to schedules that are updated according to grid constraints.

Clearly a huge number of Home Assistant users are affected by this.

Someone has developed an Home Assistant integration to pull load shedding data into HA. This works well.

It would seem that this could be handled generically by EMHASS by having a constraint as a schedule of when not to use grid power (in SA the applicable load shedding schedule) - or even vice versa, when to always prefer grid power. I can imagine this could be forced via the cost schedule of power  - making it exorbitantly expensive during load shedding and free when it should be used mandatorily.

**Comment by davidusb-geek** [comment]
Hi.
Yes I think that the easiest thing to do is to leave the optimization problem as it is and like you said pass it a list of `load_cost_forecast` with extremely expensive values when load shedding. 
So you will need to build this list directly into Home Assistant using templates and pass the list to EMHASS like you would do for any of the forecasts values needed by the optimization: `pv_power_forecast`, `load_power_forecast`, `load_cost_forecast` and `prod_price_forecast`.
