### ISSUE TITLE
When using the custom names there are no attributes is the sensors

### ISSUE THREAD

**Issue by gieljnssns** [davidusb-geek/emhass#93]
**Describe the bug**
When I use custom entity names there are no attrfibutes exposed
**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
I expected to see the attributes

**Screenshots**
<img width="508" alt="Scherm­afbeelding 2023-06-26 om 18 19 40" src="https://github.com/davidusb-geek/emhass/assets/17234951/ce121ba9-72e9-42fa-baa1-96b278b93e90">

<img width="532" alt="Scherm­afbeelding 2023-06-26 om 18 25 17" src="https://github.com/davidusb-geek/emhass/assets/17234951/acb08219-5576-4186-811e-53de05ca8999">

<img width="533" alt="Scherm­afbeelding 2023-06-26 om 18 25 40" src="https://github.com/davidusb-geek/emhass/assets/17234951/27c6170a-6053-484e-b992-b5fc39295b8c">

<img width="539" alt="Scherm­afbeelding 2023-06-26 om 18 25 52" src="https://github.com/davidusb-geek/emhass/assets/17234951/307fe389-eb3f-49d8-9b5f-2db10fd5e188">

**Home Assistant installation type**
 - Home Assistant OS

**Your hardware**
- OS: HA OS
- Architecture: amd64

**EMHASS installation type**
 - Add-on

**Additional context**
```
publish_data:
  url: http://localhost:5001/action/publish-data
  method: POST
  content_type: "application/json"
  payload: >-
    {
      "custom_deferrable_forecast_id": [
        {"entity_id": "sensor.emhass_wasmachien",
          "unit_of_measurement": "W",
          "friendly_name": "Emhass wasmachien"},
        {"entity_id": "sensor.emhass_droogkast",
          "unit_of_measurement": "W",
          "friendly_name": "Emhass droogkast"},
        {"entity_id": "sensor.emhass_afwasmachien",
          "unit_of_measurement": "W",
          "friendly_name": "Emhass afwasmachien"},
        {"entity_id": "sensor.emhass_warmtepompboiler",
          "unit_of_measurement": "W",
          "friendly_name": "Emhass warmtepompboiler"
        }
      ],
      "custom_pv_forecast_id": {
        "entity_id": "sensor.emhass_pv_forecast",
        "unit_of_measurement": "W",
        "friendly_name": "Emhass pv forecast"},
      "custom_load_forecast_id": {
        "entity_id": "sensor.emhass_load_forecast",
        "unit_of_measurement": "W",
        "friendly_name": "Emhass load forecast"},
      "custom_grid_forecast_id": {
        "entity_id": "sensor.emhass_grid_forecast",
        "unit_of_measurement": "W",
        "friendly_name": "Emhass grid forecast"},
      "custom_unit_load_cost_id": {
        "entity_id": "sensor.emhass_load_cost",
        "unit_of_measurement": "€/kWh",
        "friendly_name": "Emhass load cost"},
      "custom_unit_prod_price_id": {
        "entity_id": "sensor.emhass_prod_price",
        "unit_of_measurement": "€/kWh",
        "friendly_name": "Emhass production price"}
    }

```

**Comment by davidusb-geek** [comment]
I see why this is happening. It is a bug. I will fix it as soon as possible.

**Comment by davidusb-geek** [comment]
I've just published a new release solving this issue.
