### ISSUE TITLE
Feature Request: First power deferrable loads from battery then discharge to grid.

### ISSUE THREAD

**Issue by treynaer** [davidusb-geek/emhass#98]
Hi David,
I'm not sure if the configuration is already possible:
How do I configure EMHASS so that it first schedules the battery to discharge and run the deferrable loads and continues load?
Then if there is remaining energy it can be exported to the grid after the deferrable load has run for the configured amount of time.
Tim

**Comment by davidusb-geek** [comment]
Hi.
No this is not possible or at least I can't see how it can be easily achieved.
What you can do is set parameter `set_nodischarge_to_grid=True` and then set an automation directly on Home Assistant to further discharge your battery when you think it could be interesting.
If anyone can point me to an easy way to include this directly in the optimization without adding too many more constraints then it is something that I can consider to include in the future.
